#pragma once

#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>

typedef enum {
    KEY_UNKNOWN = 0,
    //
    KEY_A,
    KEY_B,
    KEY_C,
    KEY_D,
    KEY_E,
    KEY_F,
    KEY_G,
    KEY_H,
    KEY_I,
    KEY_J,
    KEY_K,
    KEY_L,
    KEY_M,
    KEY_N,
    KEY_O,
    KEY_P,
    KEY_Q,
    KEY_R,
    KEY_S,
    KEY_T,
    KEY_U,
    KEY_V,
    KEY_W,
    KEY_X,
    KEY_Y,
    KEY_Z,
    //
    KEY_0,
    KEY_1,
    KEY_2,
    KEY_3,
    KEY_4,
    KEY_5,
    KEY_6,
    KEY_7,
    KEY_8,
    KEY_9,
    //
    KEY_MINUS,
    KEY_EQUAL,
    //
    KEY_LBRACKET,
    KEY_RBRACKET,
    //
    KEY_SQUOTE,
    KEY_BQUOTE,
    //
    KEY_FSLASH,
    KEY_BSLASH,
    //
    KEY_SEMICOLON,
    KEY_COMMA,
    KEY_DOT,
    //
    KEY_SPACE,
    KEY_ENTER,
    KEY_TAB,
    //
    KEY_LSHIFT,
    KEY_RSHIFT,
    KEY_LCTRL,
    KEY_RCTRL,
    KEY_CAPSLOCK,
    KEY_LALT,
    KEY_RALT,
    KEY_BACKSPACE,
    KEY_ESC,
    KEY_NUMLOCK,
    KEY_SCROLLLOCK,
    //
    KEY_CURSOR_UP,
    KEY_CURSOR_DOWN,
    KEY_CURSOR_LEFT,
    KEY_CURSOR_RIGHT,
    //
    KEY_PAGE_UP,
    KEY_PAGE_DOWN,
    //
    KEY_F1,
    KEY_F2,
    KEY_F3,
    KEY_F4,
    KEY_F5,
    KEY_F6,
    KEY_F7,
    KEY_F8,
    KEY_F9,
    KEY_F10,
    KEY_F11,
    KEY_F12,
    //
    KEY_KP_0,
    KEY_KP_1,
    KEY_KP_2,
    KEY_KP_3,
    KEY_KP_4,
    KEY_KP_5,
    KEY_KP_6,
    KEY_KP_7,
    KEY_KP_8,
    KEY_KP_9,
    KEY_KP_ENTER,
    KEY_KP_MINUS,
    KEY_KP_PLUS,
    KEY_KP_DOT,
    KEY_KP_FSLASH,
    KEY_KP_ASTERISK,
    //
    KEY_MULTIMEDIA_PREVIOUS_TRACK,
    KEY_MULTIMEDIA_NEXT_TRACK,
    KEY_MULTIMEDIA_MUTE,
    KEY_MULTIMEDIA_CALCULATOR,
    KEY_MULTIMEDIA_PLAY,
    KEY_MULTIMEDIA_STOP,
    KEY_MULTIMEDIA_VOLUME_DOWN,
    KEY_MULTIMEDIA_VOLUME_UP,
    KEY_MULTIMEDIA_WWW_HOME,
    KEY_MULTIMEDIA_WWW_SEARCH,
    KEY_MULTIMEDIA_WWW_FAVORITES,
    KEY_MULTIMEDIA_WWW_REFRESH,
    KEY_MULTIMEDIA_WWW_STOP,
    KEY_MULTIMEDIA_WWW_FORWARD,
    KEY_MULTIMEDIA_WWW_BACK,
    KEY_MULTIMEDIA_MY_COMPUTER,
    KEY_MULTIMEDIA_EMAIL,
    KEY_MULTIMEDIA_MEDIA_SELECT,
    //
    KEY_ACPI_POWER,
    KEY_ACPI_SLEEP,
    KEY_ACPI_WAKE,
    //
    KEY_HOME,
    KEY_END,
    KEY_INSERT,
    KEY_DELETE,
    KEY_LGUI,
    KEY_RGUI,
    KEY_APPS,
    //
    KEY_COUNT
} keycode_t;

/**
 * スキャンコード (Scan Code Set 1) を中間コードに変換する
 */
keycode_t scancode_to_keycode(uint8_t scancode, bool extended);